{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "84a14365",
   "metadata": {
    "papermill": {
     "duration": 0.002661,
     "end_time": "2025-12-29T17:03:52.692813",
     "exception": false,
     "start_time": "2025-12-29T17:03:52.690152",
     "status": "completed"
    },
    "tags": []
   },
   "source": [
    "# Notion AI Agent\n",
    "\n",
    "✅ Connects to my Notion workspace\n",
    "\n",
    "✅ Read and understand specific structure (DanceSport, Design My Life)\n",
    "\n",
    "✅ Displays objects in 4-level hierarchy\n",
    "\n",
    "✅ Sorts groups and items with custom ordering (Fundamentals→Open, Dance order, Forward→Backward)\n",
    "\n",
    "✅ Analyzes my workspace with Gemini AI"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "9dd39b59",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2025-12-29T17:03:52.698612Z",
     "iopub.status.busy": "2025-12-29T17:03:52.698239Z",
     "iopub.status.idle": "2025-12-29T17:04:37.726912Z",
     "shell.execute_reply": "2025-12-29T17:04:37.725844Z"
    },
    "papermill": {
     "duration": 45.034589,
     "end_time": "2025-12-29T17:04:37.729094",
     "exception": false,
     "start_time": "2025-12-29T17:03:52.694505",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "================================================================================\n",
      "📦 INSTALLING REQUIRED PACKAGES\n",
      "================================================================================\n",
      "Installing google-generativeai...\n",
      "Installing requests...\n",
      "✅ All packages installed\n",
      "\n",
      "================================================================================\n",
      "🔑 CONFIGURING API KEYS\n",
      "================================================================================\n",
      "✅ Notion API key loaded\n",
      "✅ Google API key loaded\n",
      "   Key starts with: AIzaSyBrkm...\n",
      "\n",
      "================================================================================\n",
      "🧪 TESTING GEMINI API CONNECTION\n",
      "================================================================================\n",
      "\n",
      "📡 Step 1: Testing API connectivity...\n",
      "\n",
      "🔄 Trying: gemini-2.5-flash\n",
      "   (Gemini 2.5 Flash - LATEST MODEL (December 2024))\n",
      "   Testing with simple prompt...\n",
      "   ✅ SUCCESS! Model responded: 'Hello! I am ready to analyze your Notion workspace....'\n",
      "\n",
      "================================================================================\n",
      "✅ GEMINI API CONNECTED SUCCESSFULLY\n",
      "   Using: gemini-2.5-flash\n",
      "================================================================================\n",
      "\n",
      "================================================================================\n",
      "⭐ RETRIEVING NOTION WORKSPACE\n",
      "================================================================================\n",
      "\n",
      "🔍 Searching workspace...\n",
      "✅ Found 43 total objects\n",
      "   • Pages: 41\n",
      "   • Databases: 2\n",
      "\n",
      "================================================================================\n",
      "⭐ STEP 1: FAVORITES (MAIN PAGES)\n",
      "================================================================================\n",
      "\n",
      "📋 Found 2 item(s) in Favorites:\n",
      "\n",
      "1. DanceSport Training\n",
      "   URL: https://www.notion.so/DanceSport-Training-Schedule-2d7d66cc2bce80598328fb478d215cab\n",
      "\n",
      "2. Design My Life by doing what I love!\n",
      "   URL: https://www.notion.so/Design-My-Life-by-doing-what-I-love-2c6d66cc2bce80ab84c2ce6fe51fea55\n",
      "\n",
      "================================================================================\n",
      "🎵 STEP 2: DANCE GROUPS/TOPICS\n",
      "================================================================================\n",
      "\n",
      "🔍 Searching for dance-related groups...\n",
      "✅ Found 38 dance groups\n",
      "\n",
      "🔄 Applying custom sorting...\n",
      "\n",
      "================================================================================\n",
      "📊 SORTED DANCE GROUPS\n",
      "================================================================================\n",
      "\n",
      "Total: 38 groups\n",
      "\n",
      "────────────────────────────────────────────────────────────────────────────────\n",
      "  FUNDAMENTALS\n",
      "────────────────────────────────────────────────────────────────────────────────\n",
      "\n",
      "1. 📄 Fundamentals - Cha Cha\n",
      "2. 📄 Fundamentals - Rumba\n",
      "3. 📄 Fundamentals - Swing\n",
      "4. 📄 Fundamentals - Bolero\n",
      "5. 📄 Fundamentals - Mambo\n",
      "\n",
      "────────────────────────────────────────────────────────────────────────────────\n",
      "  OPEN\n",
      "────────────────────────────────────────────────────────────────────────────────\n",
      "\n",
      "6. 📄 Open Mambo\n",
      "7. 📄 Open Mambo w/ Mykyta 01 \n",
      "8. 📄 Open Mambo w/ Mykyta 02\n",
      "9. 📄 Open Mambo w/ Mykyta 03\n",
      "10. 📄 Open Mambo w/ Mykyta 04\n",
      "11. 📄 Open Mambo w/ Mykyta 05\n",
      "12. 📄 Open Mambo w/ Mykyta 06\n",
      "13. 📄 Open Mambo w/ Mykyta 07\n",
      "14. 📄 Open Mambo w/ Mykyta 08\n",
      "15. 📄 Open Mambo w/ Mykyta 09\n",
      "16. 📄 Open Mambo w/ Mykyta 10\n",
      "17. 📄 Open Mambo w/ Mykyta 11\n",
      "18. 📄 Open Mambo w/ Mykyta 12\n",
      "19. 📄 Open Mambo w/ Mykyta 13\n",
      "20. 📄 Open Mambo w/ Mykyta 14\n",
      "21. 📄 Open Mambo w/ Mykyta 15\n",
      "22. 📄 Open Mambo w/ Mykyta 16\n",
      "23. 📄 Open Mambo w/ Mykyta 17\n",
      "24. 📄 Open Mambo w/ Mykyta 18\n",
      "25. 📄 Open Mambo w/ Mykyta 19\n",
      "26. 📄 Open Mambo w/ Mykyta 20\n",
      "27. 📄 Open Mambo w/ Mykyta 21\n",
      "28. 📄 Open Mambo w/ Mykyta 22\n",
      "\n",
      "────────────────────────────────────────────────────────────────────────────────\n",
      "  OTHER\n",
      "────────────────────────────────────────────────────────────────────────────────\n",
      "\n",
      "29. 📄 Cha Cha Walk - Forward\n",
      "30. 📄 Cha Cha Walk - Backward\n",
      "31. 📄 Rumba Walk - Forward\n",
      "32. 📄 Rumba Walk - Backward\n",
      "33. 📄 Swing Walk - Forward\n",
      "34. 📄 Swing Walk - Backward\n",
      "35. 📄 Bolero Walk - Forward\n",
      "36. 📄 Bolero Walk - Backward\n",
      "37. 📄 Mambo Walk - Forward\n",
      "38. 📄 Mambo Walk - Backward\n",
      "\n",
      "================================================================================\n",
      "🗂️  KEY DATABASES IDENTIFIED\n",
      "================================================================================\n",
      "\n",
      "Searching for databases under: DanceSport Training\n",
      "\n",
      "✅ Found 1 key database(s):\n",
      "\n",
      "1. 🗂️  Learning Items\n",
      "   Purpose: Learning Items\n",
      "   ID: 2d7d66cc-2bce-811b-8840-ec67af039a78\n",
      "\n",
      "\n",
      "================================================================================\n",
      "🤖 STEP 5: AI ANALYSIS (Using gemini-2.5-flash)\n",
      "================================================================================\n",
      "\n",
      "📊 AI Analysis Results:\n",
      "================================================================================\n",
      "\n",
      "1. Based on the workspace hierarchy, what is the main purpose of the DanceSport Training Schedule?\n",
      "--------------------------------------------------------------------------------\n",
      "Based on the workspace hierarchy, the main purpose of the DanceSport Training Schedule is to **systematically organize and track the progressive mastery of specific dance techniques and routines.**\n",
      "\n",
      "It serves as a comprehensive system for managing individual \"Learning Items,\" guiding the user from foundational dance skills across multiple styles (Fundamentals) through a detailed, sequential curriculum of advanced choreography and specific instructor-led routines (e.g., Open Mambo w/ Mykyta XX).\n",
      "\n",
      "\n",
      "2. What patterns do you notice in how the content is organized across the different groups?\n",
      "--------------------------------------------------------------------------------\n",
      "The content is organized in a clear **hierarchical and progressive structure**, moving from foundational skills to advanced application, with a strong emphasis on specific dance styles and detailed sequential learning.\n",
      "\n",
      "Here are the key patterns:\n",
      "\n",
      "1.  **Skill Level Progression:** A primary distinction is made between \"Fundamentals\" and \"Open\" levels, indicating a clear path from basic mastery to more advanced or competitive training.\n",
      "2.  **Dance-Specific Grouping:** Content is first categorized by individual dance styles (Cha Cha, Rumba, Swing, Bolero, Mambo) at the fundamental level.\n",
      "3.  **Specialized Deep Dive:** The \"Open\" section reveals a disproportionate and highly granular focus on **Mambo**. This suggests a current specialization, intensive training period, or a specific curriculum dedicated to this one dance.\n",
      "4.  **Sequential, Instructor-Led Curriculum:** Within \"Open Mambo,\" the numbering system (\"w/ Mykyta 01\" to \"19\") indicates a highly structured, linear progression of specific lessons, routines, or choreographies taught by a particular instructor (Mykyta). This signifies a systematic, step-by-step learning journey.\n",
      "\n",
      "\n",
      "3. What insights can you provide about the user's interests or activities based on this structure?\n",
      "--------------------------------------------------------------------------------\n",
      "This user is a **highly dedicated and systematic DanceSport enthusiast** with a clear progression plan.\n",
      "\n",
      "Here's a concise analysis:\n",
      "\n",
      "1.  **Systematic and Dedicated Learner:** The use of Notion, a \"Learning Items\" database, and the clear \"Fundamentals\" to \"Open\" progression demonstrates a serious, organized, and goal-oriented approach to DanceSport training. They are not just casually learning but actively tracking and structuring their development.\n",
      "\n",
      "2.  **Broad Foundational Interest:** The inclusion of fundamentals for Cha Cha, Rumba, Swing, Bolero, and Mambo indicates a desire to build a comprehensive and well-rounded base across several key Latin/Rhythm dance styles.\n",
      "\n",
      "3.  **Intense Specialization in Advanced Mambo:** This is the most striking insight. The overwhelming number of \"Open Mambo\" entries (20 out of 38 total dance groups), particularly the structured series \"w/ Mykyta 01-19,\" reveals a profound and current focus on mastering Mambo at an advanced level. This strongly suggests the user is either:\n",
      "    *   Deeply passionate about Mambo and committed to achieving a high level of proficiency.\n",
      "    *   Engaged in a specific, long-term training program or private coaching with \"Mykyta\" for Mambo, possibly preparing for competition or performance in that style.\n",
      "\n",
      "================================================================================\n",
      "✅ AI ANALYSIS COMPLETE\n",
      "================================================================================\n",
      "\n",
      "================================================================================\n",
      "📊 EXECUTION SUMMARY\n",
      "================================================================================\n",
      "\n",
      "✅ Gemini Model: gemini-2.5-flash\n",
      "✅ Favorites: 2\n",
      "✅ Key Databases: 1\n",
      "   • Learning Items\n",
      "✅ Dance Groups: 38\n",
      "   • Fundamentals: 5\n",
      "   • Open: 23\n",
      "✅ AI Analysis: 3 questions answered\n",
      "\n",
      "================================================================================\n",
      "✅ ALL STEPS COMPLETE\n",
      "================================================================================\n",
      "\n"
     ]
    }
   ],
   "source": [
    "# Notion with Gemini 2.5 AI Analysis - Latest Model\n",
    "# Uses Google's latest Gemini 2.5 Flash model via API\n",
    "\n",
    "import subprocess\n",
    "import sys\n",
    "import warnings\n",
    "warnings.filterwarnings('ignore')\n",
    "\n",
    "print(\"=\" * 80)\n",
    "print(\"📦 INSTALLING REQUIRED PACKAGES\")\n",
    "print(\"=\" * 80)\n",
    "\n",
    "# Install packages\n",
    "packages = [\"google-generativeai\", \"requests\"]\n",
    "for package in packages:\n",
    "    print(f\"Installing {package}...\")\n",
    "    subprocess.run([sys.executable, \"-m\", \"pip\", \"install\", \"-q\", package], capture_output=True)\n",
    "print(\"✅ All packages installed\\n\")\n",
    "\n",
    "import requests\n",
    "import time\n",
    "from kaggle_secrets import UserSecretsClient\n",
    "import google.generativeai as genai\n",
    "\n",
    "# ============================================================================\n",
    "# SETUP API KEYS\n",
    "# ============================================================================\n",
    "\n",
    "print(\"=\" * 80)\n",
    "print(\"🔑 CONFIGURING API KEYS\")\n",
    "print(\"=\" * 80)\n",
    "\n",
    "user_secrets = UserSecretsClient()\n",
    "NOTION_TOKEN = user_secrets.get_secret(\"NOTION_TOKEN\")\n",
    "GOOGLE_API_KEY = user_secrets.get_secret(\"GOOGLE_API_KEY\")\n",
    "\n",
    "print(\"✅ Notion API key loaded\")\n",
    "print(\"✅ Google API key loaded\")\n",
    "print(f\"   Key starts with: {GOOGLE_API_KEY[:10]}...\")\n",
    "print()\n",
    "\n",
    "# Configure Gemini\n",
    "genai.configure(api_key=GOOGLE_API_KEY)\n",
    "\n",
    "# ============================================================================\n",
    "# TEST GEMINI API CONNECTION\n",
    "# ============================================================================\n",
    "\n",
    "print(\"=\" * 80)\n",
    "print(\"🧪 TESTING GEMINI API CONNECTION\")\n",
    "print(\"=\" * 80)\n",
    "\n",
    "print(\"\\n📡 Step 1: Testing API connectivity...\")\n",
    "\n",
    "# Try the latest Gemini models in order of preference\n",
    "model_options = [\n",
    "    {\n",
    "        'name': 'gemini-2.5-flash',\n",
    "        'description': 'Gemini 2.5 Flash - LATEST MODEL (December 2024)'\n",
    "    },\n",
    "    {\n",
    "        'name': 'models/gemini-2.5-flash',\n",
    "        'description': 'Gemini 2.5 Flash - Alternative path'\n",
    "    },\n",
    "    {\n",
    "        'name': 'gemini-2.0-flash-exp',\n",
    "        'description': 'Gemini 2.0 Flash (Experimental) - Cutting-edge model'\n",
    "    },\n",
    "    {\n",
    "        'name': 'gemini-2.0-flash',\n",
    "        'description': 'Gemini 2.0 Flash - Stable model'\n",
    "    },\n",
    "    {\n",
    "        'name': 'gemini-1.5-flash-latest',\n",
    "        'description': 'Gemini 1.5 Flash - Previous generation'\n",
    "    },\n",
    "    {\n",
    "        'name': 'gemini-1.5-pro-latest',\n",
    "        'description': 'Gemini 1.5 Pro - Previous generation (more capable)'\n",
    "    }\n",
    "]\n",
    "\n",
    "working_model = None\n",
    "working_model_name = None\n",
    "\n",
    "for model_option in model_options:\n",
    "    model_name = model_option['name']\n",
    "    description = model_option['description']\n",
    "    \n",
    "    print(f\"\\n🔄 Trying: {model_name}\")\n",
    "    print(f\"   ({description})\")\n",
    "    \n",
    "    try:\n",
    "        # Initialize model\n",
    "        test_model = genai.GenerativeModel(\n",
    "            model_name,\n",
    "            generation_config={\n",
    "                'temperature': 0.7,\n",
    "                'top_p': 0.95,\n",
    "                'max_output_tokens': 2048,\n",
    "            }\n",
    "        )\n",
    "        \n",
    "        # Test with a simple prompt\n",
    "        print(\"   Testing with simple prompt...\")\n",
    "        test_response = test_model.generate_content(\"Say 'Hello! I am ready to analyze your Notion workspace.'\")\n",
    "        \n",
    "        # Check if we got a response\n",
    "        if test_response and test_response.text:\n",
    "            print(f\"   ✅ SUCCESS! Model responded: '{test_response.text[:60]}...'\")\n",
    "            working_model = test_model\n",
    "            working_model_name = model_name\n",
    "            break\n",
    "        else:\n",
    "            print(f\"   ❌ Model initialized but no response received\")\n",
    "    \n",
    "    except Exception as e:\n",
    "        error_msg = str(e)\n",
    "        print(f\"   ❌ Failed: {error_msg[:100]}\")\n",
    "        \n",
    "        # Provide specific troubleshooting for common errors\n",
    "        if \"API key not valid\" in error_msg:\n",
    "            print(\"\\n\" + \"!\" * 80)\n",
    "            print(\"⚠️  API KEY ERROR\")\n",
    "            print(\"!\" * 80)\n",
    "            print(\"Your Google API key appears to be invalid.\")\n",
    "            print(\"\\n🔧 How to fix:\")\n",
    "            print(\"1. Go to https://aistudio.google.com/app/apikey\")\n",
    "            print(\"2. Create a new API key\")\n",
    "            print(\"3. In Kaggle: Add-ons > Secrets > Add Secret\")\n",
    "            print(\"   Name: GOOGLE_API_KEY\")\n",
    "            print(\"   Value: [your new API key]\")\n",
    "            print(\"4. Restart this notebook\")\n",
    "            print(\"!\" * 80 + \"\\n\")\n",
    "            sys.exit(1)\n",
    "        \n",
    "        elif \"ResourceExhausted\" in error_msg:\n",
    "            print(\"   ⚠️  Rate limit reached, trying next model...\")\n",
    "        \n",
    "        elif \"404\" in error_msg or \"not found\" in error_msg.lower():\n",
    "            print(\"   ⚠️  Model not available in your region or project\")\n",
    "        \n",
    "        continue\n",
    "\n",
    "if working_model is None:\n",
    "    print(\"\\n\" + \"!\" * 80)\n",
    "    print(\"❌ COULD NOT CONNECT TO ANY GEMINI MODEL\")\n",
    "    print(\"!\" * 80)\n",
    "    print(\"\\n🔧 Troubleshooting Steps:\")\n",
    "    print(\"\\n1. CHECK KAGGLE INTERNET ACCESS:\")\n",
    "    print(\"   • Click Settings (right sidebar)\")\n",
    "    print(\"   • Under 'Internet', ensure it's set to 'Internet on'\")\n",
    "    print(\"   • Save and restart the kernel\")\n",
    "    print(\"\\n2. VERIFY YOUR API KEY:\")\n",
    "    print(\"   • Go to https://aistudio.google.com/app/apikey\")\n",
    "    print(\"   • Make sure your API key is active\")\n",
    "    print(\"   • Copy the full key\")\n",
    "    print(\"\\n3. UPDATE KAGGLE SECRET:\")\n",
    "    print(\"   • In Kaggle: Add-ons > Secrets\")\n",
    "    print(\"   • Find GOOGLE_API_KEY\")\n",
    "    print(\"   • Update with your API key\")\n",
    "    print(\"   • Restart notebook\")\n",
    "    print(\"\\n4. CHECK QUOTA:\")\n",
    "    print(\"   • Go to https://aistudio.google.com/app/apikey\")\n",
    "    print(\"   • Check if you have remaining quota\")\n",
    "    print(\"!\" * 80 + \"\\n\")\n",
    "    sys.exit(1)\n",
    "\n",
    "print(\"\\n\" + \"=\" * 80)\n",
    "print(f\"✅ GEMINI API CONNECTED SUCCESSFULLY\")\n",
    "print(f\"   Using: {working_model_name}\")\n",
    "print(\"=\" * 80 + \"\\n\")\n",
    "\n",
    "# ============================================================================\n",
    "# NOTION CLIENT SETUP\n",
    "# ============================================================================\n",
    "\n",
    "class NotionClient:\n",
    "    def __init__(self, token):\n",
    "        self.headers = {\n",
    "            \"Authorization\": f\"Bearer {token}\",\n",
    "            \"Content-Type\": \"application/json\",\n",
    "            \"Notion-Version\": \"2022-06-28\"\n",
    "        }\n",
    "    \n",
    "    def search_all(self):\n",
    "        url = \"https://api.notion.com/v1/search\"\n",
    "        response = requests.post(url, headers=self.headers, json={\"page_size\": 100})\n",
    "        return response.json()\n",
    "\n",
    "notion = NotionClient(NOTION_TOKEN)\n",
    "\n",
    "def get_title(obj):\n",
    "    \"\"\"Extract title from page or database\"\"\"\n",
    "    if obj.get('object') == 'page':\n",
    "        properties = obj.get('properties', {})\n",
    "        for prop in properties.values():\n",
    "            if prop.get('type') == 'title':\n",
    "                titles = prop.get('title', [])\n",
    "                if titles:\n",
    "                    return titles[0].get('plain_text', 'Untitled')\n",
    "    elif obj.get('object') == 'database':\n",
    "        titles = obj.get('title', [])\n",
    "        if titles:\n",
    "            return titles[0].get('plain_text', 'Untitled')\n",
    "    return 'Untitled'\n",
    "\n",
    "# ============================================================================\n",
    "# GET NOTION CONTENT\n",
    "# ============================================================================\n",
    "\n",
    "print(\"=\" * 80)\n",
    "print(\"⭐ RETRIEVING NOTION WORKSPACE\")\n",
    "print(\"=\" * 80)\n",
    "\n",
    "print(\"\\n🔍 Searching workspace...\")\n",
    "all_results = notion.search_all()\n",
    "all_objects = all_results.get('results', [])\n",
    "\n",
    "pages = [obj for obj in all_objects if obj.get('object') == 'page']\n",
    "databases = [obj for obj in all_objects if obj.get('object') == 'database']\n",
    "\n",
    "print(f\"✅ Found {len(all_objects)} total objects\")\n",
    "print(f\"   • Pages: {len(pages)}\")\n",
    "print(f\"   • Databases: {len(databases)}\")\n",
    "\n",
    "# ============================================================================\n",
    "# STEP 1: FAVORITES\n",
    "# ============================================================================\n",
    "\n",
    "print(\"\\n\" + \"=\" * 80)\n",
    "print(\"⭐ STEP 1: FAVORITES (MAIN PAGES)\")\n",
    "print(\"=\" * 80)\n",
    "\n",
    "favorites = []\n",
    "\n",
    "for page in pages:\n",
    "    parent = page.get('parent', {})\n",
    "    if parent.get('type') == 'workspace':\n",
    "        title = get_title(page)\n",
    "        favorites.append({\n",
    "            'title': title,\n",
    "            'id': page.get('id'),\n",
    "            'url': page.get('url')\n",
    "        })\n",
    "\n",
    "print(f\"\\n📋 Found {len(favorites)} item(s) in Favorites:\\n\")\n",
    "\n",
    "for i, fav in enumerate(favorites, 1):\n",
    "    print(f\"{i}. {fav['title']}\")\n",
    "    print(f\"   URL: {fav['url']}\\n\")\n",
    "\n",
    "# ============================================================================\n",
    "# STEP 2: DANCE GROUPS\n",
    "# ============================================================================\n",
    "\n",
    "print(\"=\" * 80)\n",
    "print(\"🎵 STEP 2: DANCE GROUPS/TOPICS\")\n",
    "print(\"=\" * 80)\n",
    "\n",
    "print(\"\\n🔍 Searching for dance-related groups...\")\n",
    "\n",
    "dance_keywords = ['cha cha', 'rumba', 'swing', 'bolero', 'mambo', \n",
    "                  'fundamental', 'open', 'walk']\n",
    "\n",
    "dance_groups = []\n",
    "\n",
    "for db in databases:\n",
    "    title = get_title(db)\n",
    "    if any(keyword in title.lower() for keyword in dance_keywords):\n",
    "        dance_groups.append({\n",
    "            'title': title,\n",
    "            'id': db.get('id'),\n",
    "            'url': db.get('url'),\n",
    "            'type': 'database'\n",
    "        })\n",
    "\n",
    "for page in pages:\n",
    "    title = get_title(page)\n",
    "    is_dance_related = any(keyword in title.lower() for keyword in dance_keywords)\n",
    "    is_favorite = any(fav['id'] == page.get('id') for fav in favorites)\n",
    "    \n",
    "    if is_dance_related and not is_favorite:\n",
    "        dance_groups.append({\n",
    "            'title': title,\n",
    "            'id': page.get('id'),\n",
    "            'url': page.get('url'),\n",
    "            'type': 'page'\n",
    "        })\n",
    "\n",
    "print(f\"✅ Found {len(dance_groups)} dance groups\")\n",
    "\n",
    "# ============================================================================\n",
    "# STEP 3: CUSTOM SORTING\n",
    "# ============================================================================\n",
    "\n",
    "print(\"\\n🔄 Applying custom sorting...\")\n",
    "\n",
    "def sort_dance_groups(group):\n",
    "    title = group['title'].lower()\n",
    "    dance_order = ['cha cha', 'rumba', 'swing', 'bolero', 'mambo']\n",
    "    \n",
    "    priority1 = 0 if 'fundamental' in title else (1 if 'open' in title else 2)\n",
    "    \n",
    "    priority2 = 999\n",
    "    for idx, dance in enumerate(dance_order):\n",
    "        if dance in title:\n",
    "            priority2 = idx\n",
    "            break\n",
    "    \n",
    "    priority3 = 0 if 'forward' in title else (1 if 'backward' in title else 2) if 'walk' in title else 0\n",
    "    \n",
    "    return (priority1, priority2, priority3, title)\n",
    "\n",
    "dance_groups.sort(key=sort_dance_groups)\n",
    "\n",
    "# ============================================================================\n",
    "# STEP 4: DISPLAY SORTED GROUPS\n",
    "# ============================================================================\n",
    "\n",
    "print(\"\\n\" + \"=\" * 80)\n",
    "print(\"📊 SORTED DANCE GROUPS\")\n",
    "print(\"=\" * 80)\n",
    "\n",
    "print(f\"\\nTotal: {len(dance_groups)} groups\\n\")\n",
    "\n",
    "current_category = None\n",
    "\n",
    "for i, group in enumerate(dance_groups, 1):\n",
    "    title = group['title']\n",
    "    title_lower = title.lower()\n",
    "    \n",
    "    category = \"FUNDAMENTALS\" if 'fundamental' in title_lower else (\"OPEN\" if 'open' in title_lower else \"OTHER\")\n",
    "    \n",
    "    if category != current_category:\n",
    "        if i > 1:\n",
    "            print()\n",
    "        print(f\"{'─' * 80}\")\n",
    "        print(f\"  {category}\")\n",
    "        print(f\"{'─' * 80}\\n\")\n",
    "        current_category = category\n",
    "    \n",
    "    type_icon = \"🗂️\" if group['type'] == 'database' else \"📄\"\n",
    "    print(f\"{i}. {type_icon} {title}\")\n",
    "\n",
    "# ============================================================================\n",
    "# STEP 4.5: IDENTIFY KEY DATABASES\n",
    "# ============================================================================\n",
    "\n",
    "print(\"\\n\" + \"=\" * 80)\n",
    "print(\"🗂️  KEY DATABASES IDENTIFIED\")\n",
    "print(\"=\" * 80)\n",
    "\n",
    "# Initialize\n",
    "key_databases = []\n",
    "\n",
    "# Find DanceSport page\n",
    "dancesport_page_obj = None\n",
    "for fav in favorites:\n",
    "    if 'dancesport' in fav['title'].lower():\n",
    "        dancesport_page_obj = fav\n",
    "        break\n",
    "\n",
    "if dancesport_page_obj:\n",
    "    print(f\"\\nSearching for databases under: {dancesport_page_obj['title']}\")\n",
    "    \n",
    "    # Find databases that are children of DanceSport\n",
    "    # Look for specific database names\n",
    "    \n",
    "    for db in databases:\n",
    "        title = get_title(db)\n",
    "        title_lower = title.lower()\n",
    "        \n",
    "        # Check for key database indicators\n",
    "        is_overall_progress = ('overall' in title_lower and 'progress' in title_lower) or ('topics' in title_lower and 'progress' in title_lower)\n",
    "        is_learning_items = 'learning' in title_lower and 'items' in title_lower\n",
    "        \n",
    "        if is_overall_progress or is_learning_items:\n",
    "            key_databases.append({\n",
    "                'title': title,\n",
    "                'id': db.get('id'),\n",
    "                'type': 'Overall Learning Progress' if is_overall_progress else 'Learning Items'\n",
    "            })\n",
    "    \n",
    "    if key_databases:\n",
    "        print(f\"\\n✅ Found {len(key_databases)} key database(s):\\n\")\n",
    "        for i, db in enumerate(key_databases, 1):\n",
    "            print(f\"{i}. 🗂️  {db['title']}\")\n",
    "            print(f\"   Purpose: {db['type']}\")\n",
    "            print(f\"   ID: {db['id']}\\n\")\n",
    "    else:\n",
    "        print(\"\\n⚠️  No key databases found matching expected names\")\n",
    "        print(\"   Looking for: 'Overall Learning Progress' or 'Learning Items'\")\n",
    "else:\n",
    "    print(\"\\n⚠️  DanceSport Training Schedule page not found in favorites\")\n",
    "\n",
    "# ============================================================================\n",
    "# STEP 5: GEMINI AI ANALYSIS\n",
    "# ============================================================================\n",
    "\n",
    "print(\"\\n\" + \"=\" * 80)\n",
    "print(f\"🤖 STEP 5: AI ANALYSIS (Using {working_model_name})\")\n",
    "print(\"=\" * 80)\n",
    "\n",
    "analysis_questions = [\n",
    "    \"Based on the workspace hierarchy, what is the main purpose of the DanceSport Training Schedule?\",\n",
    "    \"What patterns do you notice in how the content is organized across the different groups?\",\n",
    "    \"What insights can you provide about the user's interests or activities based on this structure?\"\n",
    "]\n",
    "\n",
    "# Build context\n",
    "dancesport_fav = None\n",
    "for fav in favorites:\n",
    "    if 'dancesport' in fav['title'].lower():\n",
    "        dancesport_fav = fav\n",
    "        break\n",
    "\n",
    "context = f\"\"\"Analyze this DanceSport Training Schedule from Notion:\n",
    "\n",
    "MAIN PAGE: {dancesport_fav['title'] if dancesport_fav else 'DanceSport Training Schedule'}\n",
    "\n",
    "\"\"\"\n",
    "\n",
    "if key_databases:\n",
    "    context += \"KEY DATABASES:\\n\"\n",
    "    for db in key_databases:\n",
    "        context += f\"  • {db['title']} ({db['type']})\\n\"\n",
    "    context += \"\\n\"\n",
    "\n",
    "context += f\"DANCE GROUPS/TOPICS ({len(dance_groups)} total):\\n\"\n",
    "\n",
    "fundamentals = [g for g in dance_groups if 'fundamental' in g['title'].lower()]\n",
    "opens = [g for g in dance_groups if 'open' in g['title'].lower()]\n",
    "\n",
    "if fundamentals:\n",
    "    context += f\"\\nFUNDAMENTALS ({len(fundamentals)} groups):\\n\"\n",
    "    for g in fundamentals[:20]:\n",
    "        context += f\"  • {g['title']}\\n\"\n",
    "\n",
    "if opens:\n",
    "    context += f\"\\nOPEN ({len(opens)} groups):\\n\"\n",
    "    for g in opens[:20]:\n",
    "        context += f\"  • {g['title']}\\n\"\n",
    "\n",
    "context += f\"\"\"\n",
    "STRUCTURE INSIGHTS:\n",
    "• Dance styles: Cha Cha, Rumba, Swing, Bolero, Mambo\n",
    "• Skill levels: Fundamentals and Open\n",
    "• Walk types: Forward and Backward variations\n",
    "• Systematic progression from fundamentals to advanced\n",
    "\"\"\"\n",
    "\n",
    "print(\"\\n📊 AI Analysis Results:\")\n",
    "print(\"=\" * 80)\n",
    "\n",
    "for i, question in enumerate(analysis_questions, 1):\n",
    "    print(f\"\\n{i}. {question}\")\n",
    "    print(\"-\" * 80)\n",
    "    \n",
    "    prompt = f\"\"\"{context}\n",
    "\n",
    "Question: {question}\n",
    "\n",
    "Provide a concise and insightful analysis.\"\"\"\n",
    "    \n",
    "    try:\n",
    "        response = working_model.generate_content(prompt)\n",
    "        print(response.text)\n",
    "        print()\n",
    "        \n",
    "        if i < len(analysis_questions):\n",
    "            time.sleep(2)  # Small delay between requests\n",
    "    \n",
    "    except Exception as e:\n",
    "        print(f\"❌ Error generating response: {str(e)}\\n\")\n",
    "        break\n",
    "\n",
    "print(\"=\" * 80)\n",
    "print(\"✅ AI ANALYSIS COMPLETE\")\n",
    "print(\"=\" * 80)\n",
    "\n",
    "# ============================================================================\n",
    "# SUMMARY\n",
    "# ============================================================================\n",
    "\n",
    "print(\"\\n\" + \"=\" * 80)\n",
    "print(\"📊 EXECUTION SUMMARY\")\n",
    "print(\"=\" * 80)\n",
    "\n",
    "print(f\"\\n✅ Gemini Model: {working_model_name}\")\n",
    "print(f\"✅ Favorites: {len(favorites)}\")\n",
    "if key_databases:\n",
    "    print(f\"✅ Key Databases: {len(key_databases)}\")\n",
    "    for db in key_databases:\n",
    "        print(f\"   • {db['title']}\")\n",
    "print(f\"✅ Dance Groups: {len(dance_groups)}\")\n",
    "print(f\"   • Fundamentals: {len(fundamentals)}\")\n",
    "print(f\"   • Open: {len(opens)}\")\n",
    "print(f\"✅ AI Analysis: 3 questions answered\")\n",
    "\n",
    "print(\"\\n\" + \"=\" * 80)\n",
    "print(\"✅ ALL STEPS COMPLETE\")\n",
    "print(\"=\" * 80 + \"\\n\")"
   ]
  }
 ],
 "metadata": {
  "kaggle": {
   "accelerator": "none",
   "dataSources": [
    {
     "databundleVersionId": 14484960,
     "sourceId": 121144,
     "sourceType": "competition"
    }
   ],
   "dockerImageVersionId": 31234,
   "isGpuEnabled": false,
   "isInternetEnabled": true,
   "language": "python",
   "sourceType": "notebook"
  },
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.12"
  },
  "papermill": {
   "default_parameters": {},
   "duration": 51.314954,
   "end_time": "2025-12-29T17:04:40.982931",
   "environment_variables": {},
   "exception": null,
   "input_path": "__notebook__.ipynb",
   "output_path": "__notebook__.ipynb",
   "parameters": {},
   "start_time": "2025-12-29T17:03:49.667977",
   "version": "2.6.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
